predicthq_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: YOB85028
      user: duenasfd
      private_key_path: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PATH') }}"
      role: SYSADMIN
      warehouse: predicthq_wh
      database: predicthq_db
      schema: staging
      threads: 4
